engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
    exclude_fingerprints:
    - 93b6c216c8bfa6396128d0ed844521e4
  csslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
  - app/**
  - lib/**
  - "**.rb"
  - "**.go"
exclude_paths:
- spec/**/*
- features/**/*
- "**/vendor/**/*"
- "lib/tasks/**"
