# Site settings
title: Micropurchase
description:
email:
permalink: pretty
author:
  name: Andrew Maier
  email: andrew.maier@gsa.gov

github:
  organization: 18F
  repository: micropurchase
  default_branch: 18f-pages-internal


collections:
  pages:
    output: true
    permalink: /:path/


exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor