db:
   image: postgres:9
web:
    tty: true
    stdin_open: true
    build: .
    env_file: .env
    environment:
       DATABASE_USER: postgres
       DATABASE_NAME: postgres
       DATABASE_HOST: db
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    links:
      - db
