---
github_ids:
  - 2044     # Jacob Harris
  - 2471     # Kane Baccigulupi
  - 2970     # Andrew Maier
  - 86790    # Alan deLevie
  - 100149   # Michael Torres
  - 887429   # Tom Black
  - 4153048  # Dave Zvenyach
  - 13946800 # Kathryn Edelman
  - 9273855  # Duane Rollins
  - 6518236  # Alla Goldman
  - 5840989  # Laura Gerhardt
  - 7645362  # Patrick Bateman
  - 4803473  # Brian Hedberg
  # - 601515   # Jessie Young
