common: &default_settings
  app_name: Micropurchase
  audit_log:
    enabled: false
  browser_monitoring:
    auto_instrument: true
  capture_params: false
  developer_mode: false
  error_collector:
    capture_source: true
    enabled: true
    ignore_errors: "ActionController::RoutingError"
  license_key: <%= NewRelicCredentials.license_key %>
  log_level: info
  monitor_mode: true
  transaction_tracer:
    enabled: true
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    transaction_threshold: apdex_f

production:
  <<: *default_settings
  monitor_mode: true
